services:
  db:
    image: postgres:latest
    container_name: risebyeden-pos
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: risebyeden
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9.0.2
    container_name: risebyeden-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkeydata:/data

volumes:
  pgdata:
  valkeydata:
